baseURL = "https://fksvs.github.io/"
title = "Fatih Koçer"
theme = "whiteplain"
languageCode = 'en'

copyright = "&copy; Copyright 2025 Fatih Koçer"

[params]
    showShareIcons = false

[params.author]
    name = "Fatih Koçer"
    avatar = "lara.jpg"
    github = "fksvs"
    gitlab = "fksvs"
    linkedin = "fatihkocerc"
    reddit = "fksvsc"

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "Categories"
    identifier = "categories"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "Tags"
    identifier = "tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "Archives"
    identifier = "archives"
    url = "/archives/"
    weight = 3
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/projects/"
    weight = 4
[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 5

[[menu.footer]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 1