baseURL = "https://fksvs.github.io/"
title = "Fatih Koçer"
theme = "whiteplain"
languageCode = 'en'

copyright = "&copy; Copyright 2025 Fatih Koçer"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    showShareIcons = false

[params.author]
    name = "Fatih Koçer"
    avatar = "lara.jpg"
    github = "fksvs"
    gitlab = "fksvs"
    linkedin = "fatihkocerc"
    reddit = "fksvsc"

[taxonomies]
    category = "categories"

[[menu.main]]
    name = "Categories"
    identifier = "categories"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "Archives"
    identifier = "archives"
    url = "/archives/"
    weight = 2
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/projects/"
    weight = 3
[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 4

[[menu.footer]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 1